// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveDownload():Promise<string>;

export function DownloadMaps(arg1:string,arg2:number):Promise<void>;

export function DownloadPercent():Promise<number>;

export function DownloadedBytes():Promise<number>;

export function DownloadedFiles():Promise<number>;

export function Exit():Promise<void>;

export function LiveURL():Promise<string>;

export function LocalEnabled():Promise<boolean>;

export function NeedsUpdate(arg1:string):Promise<boolean>;

export function OS():Promise<string>;

export function OpenClientLocation(arg1:string):Promise<void>;

export function Play(arg1:string,arg2:boolean):Promise<void>;

export function Revision(arg1:string):Promise<number>;

export function ToggleLocal(arg1:boolean):Promise<void>;

export function TotalBytes():Promise<number>;

export function TotalFiles():Promise<number>;

export function Update(arg1:string):Promise<void>;

export function UpdateError():Promise<string>;

export function Version(arg1:string):Promise<string>;

export function Write(arg1:Array<number>):Promise<number>;
